"""
Configuration file for Email Automation System
Update these settings according to your requirements
"""

# Email Settings
EMAIL_CONFIG = {
    'EMAIL_USER': 'i211707@nu.edu.pk',
    'EMAIL_PASS': 'uaosbqwpuemmioob',  # Gmail App Password
    'SMTP_SERVER': 'smtp.gmail.com',
    'SMTP_PORT': 587
}

# File Analysis Settings
ANALYSIS_CONFIG = {
    'MAX_PREVIEW_LINES': 5,
    'MAX_COLUMN_DISPLAY': 10,
    'MAX_IMPORT_DISPLAY': 5,
    'MAX_FUNCTION_DISPLAY': 5
}

# Email Templates
EMAIL_TEMPLATES = {
    'DATA_REPORT': {
        'subject': 'Data Report - {filename}',
        'body': '''Dear Recipient,

Please find attached the data report: {filename}

This email was automatically generated by our Email Automation System.
The attachment has been analyzed and details are provided below.

Best regards,
Automated Email System'''
    },
    
    'WEEKLY_UPDATE': {
        'subject': 'Weekly Update - {filename}',
        'body': '''Hello,

This is your weekly data update. Please find the attached file: {filename}

File analysis and details are included below.

Thank you,
Data Team'''
    },
    
    'CUSTOM': {
        'subject': 'Custom Email - {filename}',
        'body': '''Hello,

Please find attached: {filename}

Analysis details are provided below.

Best regards,
System Administrator'''
    }
}

# Supported File Types for Analysis
SUPPORTED_EXTENSIONS = {
    'data': ['.csv', '.xlsx', '.xls', '.json'],
    'text': ['.txt', '.log', '.md'],
    'code': ['.py', '.js', '.html', '.css'],
    'documents': ['.pdf', '.doc', '.docx'],
    'images': ['.jpg', '.jpeg', '.png', '.gif', '.bmp']
}

# Logging Configuration
LOGGING_CONFIG = {
    'level': 'INFO',
    'format': '%(asctime)s - %(levelname)s - %(message)s',
    'log_file': 'email_automation.log'
}
